### **Partie 1 — Chargement et exploration**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

# Chargement du dataset
iris = load_iris()

In [7]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [10]:
iris['filename']

'iris.csv'

In [11]:
# Construction du DataFrame
df = pd.DataFrame(iris.data, columns=["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"])
df["Species"] = [iris.target_names[i] for i in iris.target]

In [13]:
print("=== 5 premières lignes ===")
display(df.head(3))

print("\n=== 5 dernières lignes ===")
display(df.tail())

=== 5 premières lignes ===

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0            5.1           3.5            1.4           0.2  setosa
1            4.9           3.0            1.4           0.2  setosa
2            4.7           3.2            1.3           0.2  setosa

=== 5 dernières lignes ===

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
145            6.7           3.0            5.2           2.3  virginica
146            6.3           2.5            5.0           1.9  virginica
147            6.5           3.0            5.2           2.0  virginica
148            6.2           3.4            5.4           2.3  virginica
149            5.9           3.0            5.1           1.8  virginica

In [14]:

# Forme du DataFrame
print("Shape:", df.shape)
print(f"\n{df.shape[0]} lignes, {df.shape[1]} colonnes")

Shape: (150, 5)

150 lignes, 5 colonnes

In [15]:

# Info et describe
print("=== df.info() ===")
df.info()

print("\n=== df.describe() ===")
display(df.describe())

=== df.info() ===
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.2 KB

=== df.describe() ===

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.057333       3.758000      1.199333
std         0.828066      0.435866       1.765298      0.762238
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [16]:
print("\n=== Types de données ===")
print(df.dtypes)

=== Types de données ===
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species              str
dtype: object

### **Partie 2 — Sélections et indexation**

In [17]:
# 1. Sélection de colonnes
print("=== Colonnes SepalLengthCm et PetalLengthCm ===")
display(df[["SepalLengthCm", "PetalLengthCm"]].head())

=== Colonnes SepalLengthCm et PetalLengthCm ===

   SepalLengthCm  PetalLengthCm
0            5.1            1.4
1            4.9            1.4
2            4.7            1.3
3            4.6            1.5
4            5.0            1.4

In [18]:
# 2. loc[] : sélection par labels
print("=== loc[10:20, ['Species', 'PetalWidthCm']] ===")
display(df.loc[10:20, ["Species", "PetalWidthCm"]])

=== loc[10:20, ['Species', 'PetalWidthCm']] ===

   Species  PetalWidthCm
10  setosa           0.2
11  setosa           0.2
12  setosa           0.1
13  setosa           0.1
14  setosa           0.2
15  setosa           0.4
16  setosa           0.4
17  setosa           0.3
18  setosa           0.3
19  setosa           0.3
20  setosa           0.2

In [19]:
# 3. iloc[] : sélection par position
print("=== iloc[:5, :2] (5 premières lignes, 2 premières colonnes) ===")
display(df.iloc[:5, :2])

=== iloc[:5, :2] (5 premières lignes, 2 premières colonnes) ===

   SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6

In [20]:
# 4. Filtrage simple
print("=== Fleurs avec SepalLengthCm > 6.0 ===")
df_grand = df[df["SepalLengthCm"] > 6.0]
print(f"{len(df_grand)} fleurs trouvées")
display(df_grand.head())

=== Fleurs avec SepalLengthCm > 6.0 ===
61 fleurs trouvées

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
50            7.0           3.2            4.7           1.4  versicolor
51            6.4           3.2            4.5           1.5  versicolor
52            6.9           3.1            4.9           1.5  versicolor
54            6.5           2.8            4.6           1.5  versicolor
56            6.3           3.3            4.7           1.6  versicolor

In [21]:
# 5. Filtrage avec plusieurs conditions
print("=== SepalLengthCm > 5.5 ET PetalLengthCm < 4.0 ===")
df_filtre = df[(df["SepalLengthCm"] > 5.5) & (df["PetalLengthCm"] < 4.0)]
print(f"{len(df_filtre)} fleurs trouvées")
display(df_filtre.head())

=== SepalLengthCm > 5.5 ET PetalLengthCm < 4.0 ===
7 fleurs trouvées

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
14            5.8           4.0            1.2           0.2      setosa
15            5.7           4.4            1.5           0.4      setosa
18            5.7           3.8            1.7           0.3      setosa
64            5.6           2.9            3.6           1.3  versicolor
69            5.6           2.5            3.9           1.1  versicolor

In [22]:
# 6. Méthode query()
print("=== Espèce versicolor avec query() ===")
df_versicolor = df.query("Species == 'versicolor'")
print(f"{len(df_versicolor)} fleurs versicolor")
display(df_versicolor.head())

=== Espèce versicolor avec query() ===
50 fleurs versicolor

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
50            7.0           3.2            4.7           1.4  versicolor
51            6.4           3.2            4.5           1.5  versicolor
52            6.9           3.1            4.9           1.5  versicolor
53            5.5           2.3            4.0           1.3  versicolor
54            6.5           2.8            4.6           1.5  versicolor

### **Partie 3 — Manipulation des colonnes et lignes**

In [23]:
# Travail sur une copie pour ne pas modifier l'original
df_work = df.copy()

# 1. Ajout de PetalRatio
df_work["PetalRatio"] = df_work["PetalLengthCm"] / df_work["PetalWidthCm"]
print("=== Nouvelles colonnes ajoutées ===")
display(df_work.head())

=== Nouvelles colonnes ajoutées ===

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,PetalRatio
0,5.1,3.5,1.4,0.2,setosa,7.0
1,4.9,3.0,1.4,0.2,setosa,7.0
2,4.7,3.2,1.3,0.2,setosa,6.5
3,4.6,3.1,1.5,0.2,setosa,7.5
4,5.0,3.6,1.4,0.2,setosa,7.0

In [24]:
# 2. Ajout de SepalArea
df_work["SepalArea"] = df_work["SepalLengthCm"] * df_work["SepalWidthCm"]
print("=== Nouvelles colonnes ajoutées ===")
display(df_work.head())

=== Nouvelles colonnes ajoutées ===

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,PetalRatio,SepalArea
0,5.1,3.5,1.4,0.2,setosa,7.0,17.85
1,4.9,3.0,1.4,0.2,setosa,7.0,14.70
2,4.7,3.2,1.3,0.2,setosa,6.5,15.04
3,4.6,3.1,1.5,0.2,setosa,7.5,14.26
4,5.0,3.6,1.4,0.2,setosa,7.0,18.00

In [25]:
# 3. Colonne catégorielle Taille
def categorize_size(length):
    if length < 5.0:
        return "petite"
    elif length < 6.5:
        return "moyenne"
    else:
        return "grande"

df_work["Taille"] = df_work["SepalLengthCm"].apply(categorize_size)
display(df_work.head())
# Alternative avec np.select (plus efficace)
# conditions = [
#     df_work["SepalLengthCm"] < 5.0,
#     df_work["SepalLengthCm"] < 6.5
# ]
# choices = ["petite", "moyenne"]
# df_work["Taille"] = np.select(conditions, choices, default="grande")

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,PetalRatio,SepalArea,Taille
0,5.1,3.5,1.4,0.2,setosa,7.0,17.85,moyenne
1,4.9,3.0,1.4,0.2,setosa,7.0,14.70,petite
2,4.7,3.2,1.3,0.2,setosa,6.5,15.04,petite
3,4.6,3.1,1.5,0.2,setosa,7.5,14.26,petite
4,5.0,3.6,1.4,0.2,setosa,7.0,18.00,moyenne

In [26]:
# 4. Suppression de la colonne SepalArea
df_work = df_work.drop(columns=["SepalArea"])
print("Colonnes après suppression:", list(df_work.columns))

Colonnes après suppression: ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species', 'PetalRatio', 'Taille']

In [27]:
# 5. Suppression des lignes où SepalLengthCm < 5.0
print(f"Avant suppression: {len(df_work)} lignes")
df_work = df_work[df_work["SepalLengthCm"] >= 5.0]
print(f"Après suppression: {len(df_work)} lignes")

Avant suppression: 150 lignes
Après suppression: 128 lignes

In [28]:
# 6. Tri par PetalLengthCm décroissant
df_work = df_work.sort_values(by="PetalLengthCm", ascending=False)
print("=== Trié par PetalLengthCm décroissant ===")
display(df_work.head())

=== Trié par PetalLengthCm décroissant ===

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,PetalRatio,Taille
118,7.7,2.6,6.9,2.3,virginica,3.000000,grande
117,7.7,3.8,6.7,2.2,virginica,3.045455,grande
122,7.7,2.8,6.7,2.0,virginica,3.350000,grande
105,7.6,3.0,6.6,2.1,virginica,3.142857,grande
131,7.9,3.8,6.4,2.0,virginica,3.200000,grande

In [29]:
# 7. Réinitialisation de l'index
df_work = df_work.reset_index(drop=True)
print("=== Index réinitialisé ===")
display(df_work.head())

=== Index réinitialisé ===

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,PetalRatio,Taille
0,7.7,2.6,6.9,2.3,virginica,3.000000,grande
1,7.7,3.8,6.7,2.2,virginica,3.045455,grande
2,7.7,2.8,6.7,2.0,virginica,3.350000,grande
3,7.6,3.0,6.6,2.1,virginica,3.142857,grande
4,7.9,3.8,6.4,2.0,virginica,3.200000,grande

### **Partie 4 — Gestion des valeurs manquantes**

In [30]:
# Travail sur une nouvelle copie
df_nan = df.copy()

# 1. Introduction de NaN artificiels
np.random.seed(42)  # Pour reproductibilité
indices_nan = df_nan.sample(5).index
df_nan.loc[indices_nan, "PetalWidthCm"] = np.nan

print(f"Indices avec NaN: {list(indices_nan)}")

Indices avec NaN: [73, 18, 118, 78, 76]

In [31]:
# 2. Compter les valeurs manquantes
print("=== Valeurs manquantes par colonne ===")
print(df_nan.isna().sum())

=== Valeurs manquantes par colonne ===
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     5
Species          0
dtype: int64

In [32]:
# 3. Afficher les lignes avec NaN
print("=== Lignes contenant des NaN ===")
display(df_nan[df_nan.isna().any(axis=1)])

=== Lignes contenant des NaN ===

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
18             5.7           3.8            1.7           NaN      setosa
73             6.1           2.8            4.7           NaN  versicolor
76             6.8           2.8            4.8           NaN  versicolor
78             6.0           2.9            4.5           NaN  versicolor
118            7.7           2.6            6.9           NaN   virginica

In [33]:
# 4. Remplacement par la moyenne
mean_petal_width = df_nan["PetalWidthCm"].mean()
print(f"Moyenne de PetalWidthCm: {mean_petal_width:.3f}")

df_filled = df_nan.copy()
df_filled["PetalWidthCm"] = df_filled["PetalWidthCm"].fillna(mean_petal_width)

print("\nAprès fillna:")
print(df_filled.isna().sum())

Moyenne de PetalWidthCm: 1.194

Après fillna:
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [34]:
# 5. Suppression des lignes avec NaN (sur une copie)
df_dropped = df_nan.dropna()
print(f"Avant dropna: {len(df_nan)} lignes")
print(f"Après dropna: {len(df_dropped)} lignes")

Avant dropna: 150 lignes
Après dropna: 145 lignes